fix for MSVC error in monolithic build mode: error C4839: non-standard use of class 'std::atomic<int>' as an argument to a variadic function
The reason is that we compile leptonica in forced C++ mode and have a suitable retyped l_atomic type in there, which only shows up when you treat the codebase as C++.
The fix is a simple cast that works in both C and C++ build mode.