fix MSVC compile error due to 'verbose' being defined in the MSVC system header files, which resulting in MSVC2022 producing some *extremely weird* error reports:
        jbig2enc\src\jbig2enc.cc(542,68): error C2143: syntax error: missing ')' before '-'
        jbig2enc\src\jbig2enc.cc(542,68): error C2143: syntax error: missing ';' before '-'
        jbig2enc\src\jbig2enc.cc(542,68): error C2059: syntax error: '-'
        jbig2enc\src\jbig2enc.cc(542,75): error C2059: syntax error: ')'
        jbig2enc\src\jbig2enc.cc(542,77): error C2143: syntax error: missing ';' before '{'
        jbig2enc\src\jbig2enc.cc(542,77): error C2447: '{': missing function header (old-style formal list?)

See also previous commit which fixed this for another source file: SHA-1: 8c22d17aa10e420ae5eadebd352056afab5058ff

* fix compile-time clash with `verbose` defined in the vector system header file (MSVC/Win32)