fix MSVC errors: warning C4103: alignment changed after including header, may be due to missing #pragma pack(pop) error C2338: static_assert failed: 'Windows headers require the default packing option. Changing this can lead to memory corruption. This diagnostic can be disabled by building with WINDOWS_IGNORE_PACKING_MISMATCH defined.' (compiling source file ../../thirdparty/owemdjee/jbig2enc/src/jbig2enc.cc) warning C4324: 'WIN32_MEMORY_PARTITION_INFORMATION': structure was padded due to alignment specifier